/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 src\models\laptop.glb
Author: GeniusPilot2016 (https://sketchfab.com/GeniusPilot2016)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/laptop-676e365f61f544e9a0236b7519e1bc90
Title: Laptop
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import model from './laptop.glb'

export function ModelLaptop(props) {
  const { nodes, materials } = useGLTF(model)
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.021, 0.454]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.120}>
        <mesh geometry={nodes.Object_4.geometry} material={materials['case']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.touchpad} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.ports} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.holes} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.ethernet_port} />
      </group>
      <group position={[0, 0.028, 0.742]} rotation={[-1.309, 0.028, -Math.PI]} scale={[0.115, 0.055, 0.115]}>
        <mesh geometry={nodes.Object_10.geometry} material={materials['case']} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.display} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.bezel} />
      </group>
      <mesh geometry={nodes.Object_14.geometry} material={materials.keyboard} position={[0, 0.037, 0.541]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.115} />
    </group>
  )
}

useGLTF.preload(model)
