/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 src\models\solar_impulse_flight_path.glb
Author: Solar Impulse (https://sketchfab.com/solarimpulse)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/solar-impulse-flight-path-298e1ac1fdb048e892d036d588d4322c
Title: Solar Impulse Flight Path
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import model from './solar_impulse_flight_path.glb'

export function ModelEarth(props) {
  const { nodes, materials } = useGLTF(model)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials['Material.001']} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload(model)
